import { buildLeaderboard } from "@/lib/utils/leaderboard";
import type {
  BattleModel,
  ContestEntryModel,
  ContestModel,
  ContentModel,
  ConversationModel,
  CrewMemberModel,
  CrewModel,
  MessageModel,
  NotificationModel,
  ReportModel,
  UserModel,
} from "@/types/models";

const now = Date.now();
const iso = (hoursAgo: number) => new Date(now - hoursAgo * 60 * 60 * 1000).toISOString();

export const mockUsers: UserModel[] = [
  {
    id: "u1",
    username: "milanmoves",
    displayName: "Milan Moves",
    email: "milan@dreamledge.app",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80",
    bio: "Sports storyteller turning every clip into a statement.",
    categories: ["sports", "storytelling", "motivation"],
    goals: ["win contests", "get discovered"],
    socialLinks: { tiktok: "@milanmoves", youtube: "youtube.com/@milanmoves" },
    totalPoints: 1440,
    battleWins: 18,
    contestWins: 5,
    followerCount: 18400,
    followingCount: 320,
    badges: ["Top 10 Weekly", "Battle King"],
    verified: true,
    rookie: false,
    createdAt: iso(400),
    updatedAt: iso(2),
  },
  {
    id: "u2",
    username: "rileytalks",
    displayName: "Riley Talks",
    email: "riley@dreamledge.app",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=1200&q=80",
    bio: "Commentary creator blending culture, news takes, and sharp edits.",
    categories: ["commentary", "news takes", "education"],
    goals: ["grow audience", "build community"],
    socialLinks: { twitter: "x.com/rileytalks", youtube: "youtube.com/@rileytalks" },
    totalPoints: 1320,
    battleWins: 14,
    contestWins: 6,
    followerCount: 22700,
    followingCount: 410,
    badges: ["Featured Creator", "Top Commentator"],
    verified: true,
    rookie: false,
    createdAt: iso(300),
    updatedAt: iso(3),
  },
  {
    id: "u3",
    username: "jadejokes",
    displayName: "Jade Jokes",
    email: "jade@dreamledge.app",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?auto=format&fit=crop&w=1200&q=80",
    bio: "Comedy, skits, and chaos with premium pacing.",
    categories: ["comedy", "skits", "reactions"],
    goals: ["get discovered", "win contests"],
    socialLinks: { tiktok: "@jadejokes" },
    totalPoints: 1180,
    battleWins: 12,
    contestWins: 3,
    followerCount: 15400,
    followingCount: 280,
    badges: ["Funniest Clip Winner"],
    verified: false,
    rookie: true,
    createdAt: iso(180),
    updatedAt: iso(5),
  },
  {
    id: "u4",
    username: "nxtedits",
    displayName: "NXT Edits",
    email: "nxt@dreamledge.app",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80",
    bio: "Visual edit specialist making every frame feel expensive.",
    categories: ["lifestyle", "fashion", "storytelling"],
    goals: ["attract brands", "find collaborators"],
    socialLinks: { facebook: "facebook.com/nxtedits" },
    totalPoints: 990,
    battleWins: 9,
    contestWins: 2,
    followerCount: 9600,
    followingCount: 210,
    badges: ["Visual Editor"],
    verified: false,
    rookie: true,
    createdAt: iso(120),
    updatedAt: iso(7),
  },
];

export const mockContent: ContentModel[] = [
  {
    id: "c1",
    creatorId: "u1",
    platform: "youtube",
    sourceUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=800&q=80",
    title: "Underdog season, narrated like cinema",
    caption: "A sports edit built to make every second feel like the final round.",
    category: "best sports creator",
    tags: ["sports", "editing", "storytelling"],
    status: "published",
    featured: true,
    likeCount: 422,
    commentCount: 58,
    saveCount: 144,
    shareCount: 31,
    voteCount: 0,
    createdAt: iso(6),
    updatedAt: iso(2),
  },
  {
    id: "c2",
    creatorId: "u2",
    platform: "twitter",
    sourceUrl: "https://x.com/rileytalks/status/123456",
    embedUrl: "https://x.com/rileytalks/status/123456",
    thumbnailUrl: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=800&q=80",
    title: "The take everybody missed",
    caption: "Breaking down the story behind the headline with sharper context.",
    category: "best commentary",
    tags: ["commentary", "news", "culture"],
    status: "published",
    featured: true,
    likeCount: 510,
    commentCount: 74,
    saveCount: 201,
    shareCount: 80,
    voteCount: 0,
    createdAt: iso(8),
    updatedAt: iso(4),
  },
  {
    id: "c3",
    creatorId: "u3",
    platform: "tiktok",
    sourceUrl: "https://www.tiktok.com/@jadejokes/video/123",
    embedUrl: "https://www.tiktok.com/@jadejokes/video/123",
    thumbnailUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80",
    title: "POV: the group chat picks your outfit",
    caption: "Fast-cut skit energy that lands in the first three seconds.",
    category: "funniest clip",
    tags: ["comedy", "skits", "viral"],
    status: "published",
    featured: false,
    likeCount: 890,
    commentCount: 110,
    saveCount: 274,
    shareCount: 160,
    voteCount: 0,
    createdAt: iso(4),
    updatedAt: iso(2),
  },
  {
    id: "c4",
    creatorId: "u4",
    platform: "facebook",
    sourceUrl: "https://www.facebook.com/watch/?v=456",
    embedUrl: "https://www.facebook.com/watch/?v=456",
    thumbnailUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    title: "Moodboard to masterpiece in 20 seconds",
    caption: "Visual editing built for replays, saves, and brand attention.",
    category: "best visual editing",
    tags: ["fashion", "editing", "lifestyle"],
    status: "published",
    featured: false,
    likeCount: 344,
    commentCount: 36,
    saveCount: 121,
    shareCount: 19,
    voteCount: 0,
    createdAt: iso(14),
    updatedAt: iso(6),
  },
];

export const mockBattles: BattleModel[] = [
  {
    id: "b1",
    creatorAId: "u1",
    creatorBId: "u2",
    contentAId: "c1",
    contentBId: "c2",
    type: "category battle",
    category: "best creator of the week",
    theme: "Clarity vs energy",
    status: "live",
    creatorAWatchTime: 10,
    creatorBWatchTime: 7,
    creatorAJudged: true,
    creatorBJudged: false,
    creatorAScore: 8.7,
    creatorBScore: 0,
    winnerId: null,
    createdAt: iso(24),
    startAt: iso(2),
    endAt: iso(-22),
    updatedAt: iso(1),
  },
  {
    id: "b2",
    creatorAId: "u3",
    creatorBId: "u4",
    contentAId: "c3",
    contentBId: "c4",
    type: "themed battle",
    category: "best visual editing",
    theme: "High replay value",
    status: "judging",
    creatorAWatchTime: 10,
    creatorBWatchTime: 10,
    creatorAJudged: false,
    creatorBJudged: false,
    creatorAScore: 0,
    creatorBScore: 0,
    winnerId: null,
    createdAt: iso(32),
    startAt: iso(5),
    endAt: iso(-10),
    updatedAt: iso(1),
  },
];

export const mockContests: ContestModel[] = [
  {
    id: "co1",
    title: "Creator Clash Weekly",
    description: "A premium weekly showcase for the strongest new uploads across the app.",
    category: "best creator of the week",
    bannerUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80",
    rules: "Submit one public creator clip. Strong hooks, sharp edits, and originality win.",
    status: "live",
    startAt: iso(48),
    endAt: iso(-36),
    createdAt: iso(64),
  },
  {
    id: "co2",
    title: "Funniest Clip Friday",
    description: "The funniest creators battle for points, badges, and discovery.",
    category: "funniest clip",
    bannerUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
    rules: "Bring a clean punchline, great pacing, and replay-worthy moments.",
    status: "upcoming",
    startAt: iso(-12),
    endAt: iso(-60),
    createdAt: iso(24),
  },
];

export const mockContestEntries: ContestEntryModel[] = [
  { id: "ce1", contestId: "co1", creatorId: "u2", contentId: "c2", voteCount: 422, judgeScore: 9.2, rank: 1, createdAt: iso(20) },
  { id: "ce2", contestId: "co1", creatorId: "u1", contentId: "c1", voteCount: 391, judgeScore: 8.9, rank: 2, createdAt: iso(19) },
  { id: "ce3", contestId: "co2", creatorId: "u3", contentId: "c3", voteCount: 0, judgeScore: 0, rank: 0, createdAt: iso(2) },
];

export const mockConversations: ConversationModel[] = [
  { id: "cv1", participantIds: ["u1", "u2"], lastMessage: "Your commentary piece is battle-ready.", lastMessageAt: iso(1), createdAt: iso(100) },
  { id: "cv2", participantIds: ["u1", "u3"], lastMessage: "Want to run a direct challenge this weekend?", lastMessageAt: iso(6), createdAt: iso(60) },
];

export const mockMessages: MessageModel[] = [
  { id: "m1", conversationId: "cv1", senderId: "u2", body: "Your sports edit feels cinematic.", messageType: "text", createdAt: iso(5) },
  { id: "m2", conversationId: "cv1", senderId: "u1", body: "Your commentary piece is battle-ready.", messageType: "battle-invite", createdAt: iso(1) },
  { id: "m3", conversationId: "cv2", senderId: "u3", body: "Want to run a direct challenge this weekend?", messageType: "text", createdAt: iso(6) },
];

export const mockCrews: CrewModel[] = [
  {
    id: "cr1",
    name: "Signal House",
    slug: "signal-house",
    description: "Commentary, strategy, and social precision.",
    bannerUrl: "https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&w=1200&q=80",
    ownerId: "u2",
    memberCount: 12,
    totalPoints: 7120,
    createdAt: iso(300),
  },
  {
    id: "cr2",
    name: "Highlight Lab",
    slug: "highlight-lab",
    description: "Sports edits, momentum clips, and motion-first storytelling.",
    bannerUrl: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80",
    ownerId: "u1",
    memberCount: 9,
    totalPoints: 5930,
    createdAt: iso(280),
  },
];

export const mockCrewMembers: CrewMemberModel[] = [
  { id: "cm1", crewId: "cr1", userId: "u2", role: "captain", joinedAt: iso(200) },
  { id: "cm2", crewId: "cr1", userId: "u4", role: "member", joinedAt: iso(120) },
  { id: "cm3", crewId: "cr2", userId: "u1", role: "captain", joinedAt: iso(220) },
  { id: "cm4", crewId: "cr2", userId: "u3", role: "member", joinedAt: iso(110) },
];

export const mockNotifications: NotificationModel[] = [
  { id: "n1", userId: "u1", type: "battle result", actorId: "u2", targetId: "b1", targetType: "battle", read: false, createdAt: iso(1) },
  { id: "n2", userId: "u1", type: "new follower", actorId: "u4", targetId: "u1", targetType: "profile", read: true, createdAt: iso(10) },
  { id: "n3", userId: "u1", type: "message received", actorId: "u3", targetId: "cv2", targetType: "conversation", read: false, createdAt: iso(6) },
];

export const mockReports: ReportModel[] = [
  { id: "r1", reporterId: "u3", targetType: "content", targetId: "c2", reason: "misleading title", details: "Feels like clickbait wording.", status: "open", createdAt: iso(8) },
  { id: "r2", reporterId: "u4", targetType: "battle", targetId: "b1", reason: "judging dispute", details: "Watch timer felt too short in one round.", status: "reviewing", createdAt: iso(4) },
];

export const mockLeaderboard = buildLeaderboard(mockUsers, "global");
export const mockWeeklyLeaderboard = buildLeaderboard(
  mockUsers.map((user, index) => ({ ...user, totalPoints: user.totalPoints - index * 120 })),
  "weekly",
);
