import { buildLeaderboard } from "@/lib/utils/leaderboard";
import type {
  BattleModel,
  ContestEntryModel,
  ContestModel,
  ContentModel,
  ConversationModel,
  CrewMemberModel,
  CrewModel,
  MessageModel,
  NotificationModel,
  ReportModel,
  UserModel,
} from "@/types/models";

const now = Date.now();
const iso = (hoursAgo: number) => new Date(now - hoursAgo * 60 * 60 * 1000).toISOString();
const LIVE_CONTENT_MAX_AGE_MS = 24 * 60 * 60 * 1000;

export const mockUsers: UserModel[] = [
  {
    id: "u1",
    username: "sosanoir",
    displayName: "Sosa Noir",
    email: "sosa@dreamledge.app",
    photoUrl: "/sosadata.jpg",
    bannerUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80",
    bio: "Story-driven creator bringing sharp presence, raw personality, and standout energy to every post.",
    categories: ["commentary", "storytelling", "motivation"],
    goals: ["grow audience", "build community"],
    socialLinks: { instagram: "https://instagram.com/sosanoir", tiktok: "@sosanoir", youtube: "youtube.com/@sosanoir", twitch: "https://www.twitch.tv/ml7support", website: "https://sosanoir.media" },
    totalPoints: 1675,
    battleWins: 21,
    contestWins: 7,
    followerCount: 4,
    followingCount: 4,
    followerIds: ["u2", "u3", "u4", "u5"],
    followingIds: ["u2", "u3", "u4", "u5"],
    badges: ["Featured Creator", "Storyteller", "Top 10 Weekly"],
    verified: true,
    rookie: false,
    createdAt: iso(520),
    updatedAt: iso(1),
  },
  {
    id: "u2",
    username: "rileytalks",
    displayName: "Riley Talks",
    email: "riley@dreamledge.app",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=1200&q=80",
    bio: "Commentary creator blending culture, news takes, and sharp edits.",
    categories: ["commentary", "news takes", "education"],
    goals: ["grow audience", "build community"],
    socialLinks: { instagram: "https://instagram.com/rileytalks", twitter: "x.com/rileytalks", youtube: "youtube.com/@rileytalks", twitch: "https://twitch.tv/rileytalks" },
    totalPoints: 1320,
    battleWins: 14,
    contestWins: 6,
    followerCount: 4,
    followingCount: 4,
    followerIds: ["u1", "u3", "u4", "u5"],
    followingIds: ["u1", "u3", "u4", "u5"],
    badges: ["Featured Creator", "Top Commentator"],
    verified: false,
    rookie: false,
    createdAt: iso(300),
    updatedAt: iso(3),
  },
  {
    id: "u3",
    username: "jadejokes",
    displayName: "Jade Jokes",
    email: "jade@dreamledge.app",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?auto=format&fit=crop&w=1200&q=80",
    bio: "Comedy, skits, and chaos with premium pacing.",
    categories: ["comedy", "skits", "reactions"],
    goals: ["get discovered", "win contests"],
    socialLinks: { instagram: "https://instagram.com/jadejokes", tiktok: "@jadejokes", website: "https://jadejokes.club" },
    totalPoints: 1180,
    battleWins: 12,
    contestWins: 3,
    followerCount: 4,
    followingCount: 4,
    followerIds: ["u1", "u2", "u4", "u5"],
    followingIds: ["u1", "u2", "u4", "u5"],
    badges: ["Funniest Clip Winner"],
    verified: false,
    rookie: true,
    createdAt: iso(180),
    updatedAt: iso(5),
  },
  {
    id: "u4",
    username: "nxtedits",
    displayName: "NXT Edits",
    email: "nxt@dreamledge.app",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80",
    bio: "Visual edit specialist making every frame feel expensive.",
    categories: ["lifestyle", "fashion", "storytelling"],
    goals: ["attract brands", "find collaborators"],
    socialLinks: { instagram: "https://instagram.com/nxtedits", facebook: "facebook.com/nxtedits", website: "https://nxtedits.studio" },
    totalPoints: 990,
    battleWins: 9,
    contestWins: 2,
    followerCount: 4,
    followingCount: 4,
    followerIds: ["u1", "u2", "u3", "u5"],
    followingIds: ["u1", "u2", "u3", "u5"],
    badges: ["Visual Editor"],
    verified: false,
    rookie: true,
    createdAt: iso(120),
    updatedAt: iso(7),
  },
  {
    id: "u5",
    username: "berto_brown",
    displayName: "Berto Brown",
    email: "berto@dreamledge.app",
    photoUrl: "/bertdata.jpg",
    bannerUrl: "https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&w=1200&q=80",
    bio: "Sharp on camera, grounded in story, and focused on building a real audience through standout creator energy.",
    categories: ["commentary", "motivation", "storytelling"],
    goals: ["grow audience", "build community"],
    socialLinks: { instagram: "https://instagram.com/berto_brown", tiktok: "@berto_brown", youtube: "youtube.com/@bertobrown", website: "https://bertobrown.media" },
    totalPoints: 1495,
    battleWins: 17,
    contestWins: 4,
    followerCount: 4,
    followingCount: 4,
    followerIds: ["u1", "u2", "u3", "u4"],
    followingIds: ["u1", "u2", "u3", "u4"],
    badges: ["Featured Creator", "Verified Creator", "Momentum Builder"],
    verified: true,
    rookie: false,
    createdAt: iso(260),
    updatedAt: iso(2),
  },
];

export const mockContent: ContentModel[] = [
  {
    id: "c1",
    creatorId: "u1",
    platform: "youtube",
    sourceUrl: "https://www.youtube.com/watch?v=nCm1dQUowGo&list=RDnCm1dQUowGo&start_radio=1",
    embedUrl: "https://www.youtube.com/embed/nCm1dQUowGo",
    thumbnailUrl: "/sosadata.jpg",
    title: "Built from pressure, posted with purpose",
    caption: "A sharp creator intro clip from Sosa Noir, built to stop the scroll and make the brand stick.",
    category: "best commentary",
    tags: ["commentary", "storytelling", "motivation"],
    status: "published",
    featured: true,
    likeCount: 684,
    commentCount: 93,
    saveCount: 240,
    shareCount: 58,
    voteCount: 0,
    createdAt: iso(3),
    updatedAt: iso(1),
  },
  {
    id: "c2",
    creatorId: "u2",
    platform: "youtube",
    sourceUrl: "https://youtube.com/shorts/Wlc4r7tczyA",
    embedUrl: "https://youtube.com/shorts/Wlc4r7tczyA?si=3WnWE7rLhVNFblrM",
    thumbnailUrl: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=800&q=80",
    title: "The take everybody missed",
    caption: "Breaking down the story behind the headline with sharper context.",
    category: "best commentary",
    tags: ["commentary", "news", "culture"],
    status: "published",
    featured: true,
    likeCount: 510,
    commentCount: 74,
    saveCount: 201,
    shareCount: 80,
    voteCount: 0,
    createdAt: iso(8),
    updatedAt: iso(4),
  },
  {
    id: "c3",
    creatorId: "u3",
    platform: "tiktok",
    sourceUrl: "https://www.tiktok.com/@ishowspeed/video/7621300668329905422",
    embedUrl: "https://www.tiktok.com/@ishowspeed/video/7621300668329905422?is_from_webapp=1&sender_device=pc&web_id=7628939101865051662",
    thumbnailUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80",
    title: "POV: the group chat picks your outfit",
    caption: "Fast-cut skit energy that lands in the first three seconds.",
    category: "funniest clip",
    tags: ["comedy", "skits", "viral"],
    status: "published",
    featured: false,
    likeCount: 890,
    commentCount: 110,
    saveCount: 274,
    shareCount: 160,
    voteCount: 0,
    createdAt: iso(4),
    updatedAt: iso(2),
  },
  {
    id: "c4",
    creatorId: "u4",
    platform: "youtube",
    sourceUrl: "https://youtu.be/FoKFq4cQyew",
    embedUrl: "https://www.youtube.com/embed/FoKFq4cQyew",
    thumbnailUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    title: "Moodboard to masterpiece in 20 seconds",
    caption: "Visual editing built for replays, saves, and brand attention.",
    category: "best visual editing",
    tags: ["fashion", "editing", "lifestyle"],
    status: "published",
    featured: false,
    likeCount: 344,
    commentCount: 36,
    saveCount: 121,
    shareCount: 19,
    voteCount: 0,
    createdAt: iso(14),
    updatedAt: iso(6),
  },
  {
    id: "c5",
    creatorId: "u1",
    platform: "twitch",
    sourceUrl: "https://www.twitch.tv/ml7support",
    embedUrl: "https://www.twitch.tv/ml7support",
    thumbnailUrl: "/sosadata.jpg",
    title: "Sosa Noir is live now",
    caption: "Tap in with Sosa Noir live on Twitch right now.",
    category: "live now",
    tags: ["live", "twitch", "commentary"],
    status: "live",
    featured: true,
    likeCount: 0,
    commentCount: 0,
    saveCount: 0,
    shareCount: 0,
    voteCount: 0,
    createdAt: iso(0),
    updatedAt: iso(0),
  },
  {
    id: "c6",
    creatorId: "u5",
    platform: "youtube",
    sourceUrl: "https://www.youtube.com/watch?v=Ss18tDu25gg",
    embedUrl: "https://www.youtube.com/embed/Ss18tDu25gg",
    thumbnailUrl: "https://img.youtube.com/vi/Ss18tDu25gg/hqdefault.jpg",
    title: "Berto Brown breaks it down in one take",
    caption: "One clean take, sharp delivery, and creator energy built to hold attention from the first second.",
    category: "best commentary",
    tags: ["commentary", "storytelling", "motivation"],
    status: "published",
    featured: true,
    likeCount: 612,
    commentCount: 89,
    saveCount: 214,
    shareCount: 67,
    voteCount: 0,
    createdAt: iso(5),
    updatedAt: iso(2),
  },
];

export function isContentVisible(item: ContentModel, currentTime = Date.now()): boolean {
  if (!(item.platform === "twitch" && item.status === "live")) {
    return true;
  }

  const createdAt = new Date(item.createdAt).getTime();
  if (!Number.isFinite(createdAt)) {
    return false;
  }

  return currentTime - createdAt < LIVE_CONTENT_MAX_AGE_MS;
}

export function getVisibleMockContent(currentTime = Date.now()): ContentModel[] {
  return mockContent.filter((item) => isContentVisible(item, currentTime));
}

export const mockBattles: BattleModel[] = [
  {
    id: "b1",
    creatorAId: "u1",
    creatorBId: "u2",
    contentAId: "c1",
    contentBId: "c2",
    type: "category battle",
    category: "best creator of the week",
    theme: "Clarity vs energy",
    status: "live",
    creatorAWatchTime: 10,
    creatorBWatchTime: 7,
    creatorAJudged: true,
    creatorBJudged: false,
    creatorAScore: 8.7,
    creatorBScore: 0,
    winnerId: null,
    createdAt: iso(24),
    startAt: iso(2),
    endAt: iso(-22),
    updatedAt: iso(1),
  },
  {
    id: "b2",
    creatorAId: "u3",
    creatorBId: "u4",
    contentAId: "c3",
    contentBId: "c4",
    type: "themed battle",
    category: "best visual editing",
    theme: "High replay value",
    status: "judging",
    creatorAWatchTime: 10,
    creatorBWatchTime: 10,
    creatorAJudged: false,
    creatorBJudged: false,
    creatorAScore: 0,
    creatorBScore: 0,
    winnerId: null,
    createdAt: iso(32),
    startAt: iso(5),
    endAt: iso(-10),
    updatedAt: iso(1),
  },
];

export const mockContests: ContestModel[] = [
  {
    id: "co1",
    title: "Creator Clash Weekly",
    description: "A premium weekly showcase for the strongest new uploads across the app.",
    category: "best creator of the week",
    bannerUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80",
    rules: "Submit one public creator clip. Strong hooks, sharp edits, and originality win.",
    status: "live",
    startAt: iso(48),
    endAt: iso(-36),
    createdAt: iso(64),
  },
  {
    id: "co2",
    title: "Funniest Clip Friday",
    description: "The funniest creators battle for points, badges, and discovery.",
    category: "funniest clip",
    bannerUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
    rules: "Bring a clean punchline, great pacing, and replay-worthy moments.",
    status: "upcoming",
    startAt: iso(-12),
    endAt: iso(-60),
    createdAt: iso(24),
  },
];

export const mockContestEntries: ContestEntryModel[] = [
  { id: "ce1", contestId: "co1", creatorId: "u2", contentId: "c2", voteCount: 422, judgeScore: 9.2, rank: 1, createdAt: iso(20) },
  { id: "ce2", contestId: "co1", creatorId: "u1", contentId: "c1", voteCount: 391, judgeScore: 8.9, rank: 2, createdAt: iso(19) },
  { id: "ce3", contestId: "co2", creatorId: "u3", contentId: "c3", voteCount: 0, judgeScore: 0, rank: 0, createdAt: iso(2) },
];

export const mockConversations: ConversationModel[] = [
  { id: "cv1", participantIds: ["u1", "u2"], lastMessage: "Your commentary piece is battle-ready.", lastSenderId: "u1", lastMessageAt: iso(1), createdAt: iso(100) },
  { id: "cv2", participantIds: ["u1", "u3"], lastMessage: "Want to run a direct challenge this weekend?", lastSenderId: "u3", lastMessageAt: iso(6), createdAt: iso(60) },
];

export const mockMessages: MessageModel[] = [
  { id: "m1", conversationId: "cv1", senderId: "u2", body: "Your sports edit feels cinematic.", messageType: "text", createdAt: iso(5) },
  { id: "m2", conversationId: "cv1", senderId: "u1", body: "Your commentary piece is battle-ready.", messageType: "battle-invite", createdAt: iso(1) },
  { id: "m3", conversationId: "cv2", senderId: "u3", body: "Want to run a direct challenge this weekend?", messageType: "text", createdAt: iso(6) },
];

export const mockCrews: CrewModel[] = [
  {
    id: "cr1",
    name: "Signal House",
    slug: "signal-house",
    description: "Commentary, strategy, and social precision.",
    bannerUrl: "https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&w=1200&q=80",
    ownerId: "u2",
    memberCount: 12,
    totalPoints: 7120,
    createdAt: iso(300),
  },
  {
    id: "cr2",
    name: "Highlight Lab",
    slug: "highlight-lab",
    description: "Sports edits, momentum clips, and motion-first storytelling.",
    bannerUrl: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80",
    ownerId: "u1",
    memberCount: 9,
    totalPoints: 5930,
    createdAt: iso(280),
  },
];

export const mockCrewMembers: CrewMemberModel[] = [
  { id: "cm1", crewId: "cr1", userId: "u2", role: "captain", joinedAt: iso(200) },
  { id: "cm2", crewId: "cr1", userId: "u4", role: "member", joinedAt: iso(120) },
  { id: "cm3", crewId: "cr2", userId: "u1", role: "captain", joinedAt: iso(220) },
  { id: "cm4", crewId: "cr2", userId: "u3", role: "member", joinedAt: iso(110) },
];

export const mockNotifications: NotificationModel[] = [
  { id: "n1", userId: "u1", type: "battle result", actorId: "u2", targetId: "b1", targetType: "battle", read: false, createdAt: iso(1) },
  { id: "n2", userId: "u1", type: "new follower", actorId: "u4", targetId: "u1", targetType: "profile", read: true, createdAt: iso(10) },
  { id: "n3", userId: "u1", type: "message received", actorId: "u3", targetId: "cv2", targetType: "conversation", read: false, createdAt: iso(6) },
];

export const mockReports: ReportModel[] = [
  { id: "r1", reporterId: "u3", targetType: "content", targetId: "c2", reason: "misleading title", details: "Feels like clickbait wording.", status: "open", createdAt: iso(8) },
  { id: "r2", reporterId: "u4", targetType: "battle", targetId: "b1", reason: "judging dispute", details: "Watch timer felt too short in one round.", status: "reviewing", createdAt: iso(4) },
];

export const mockLeaderboard = buildLeaderboard(mockUsers, "global");
export const mockWeeklyLeaderboard = buildLeaderboard(
  mockUsers.map((user, index) => ({ ...user, totalPoints: user.totalPoints - index * 120 })),
  "weekly",
);
